# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('idAno', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'ordering': ['idAno'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['idDepartamento'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idMes', models.AutoField(primary_key=True, serialize=False)),
                ('inicioPeriodo', models.DateField()),
                ('finalPeriodo', models.DateField()),
            ],
            options={
                'ordering': ['idMes'],
            },
        ),
        migrations.CreateModel(
            name='PrecioCombustible',
            fields=[
                ('idPrecioCom', models.AutoField(primary_key=True, serialize=False)),
                ('precioCombustible', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idAno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Ano')),
                ('idMes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Periodo')),
            ],
            options={
                'ordering': ['idAno'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['idProducto'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['idRol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('nombreUsuario', models.CharField(max_length=30)),
                ('apellidoUsuario', models.CharField(max_length=30)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Rol')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idZona', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['idZona'],
            },
        ),
        migrations.AddField(
            model_name='preciocombustible',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Producto'),
        ),
        migrations.AddField(
            model_name='preciocombustible',
            name='idZona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Zona'),
        ),
        migrations.AddField(
            model_name='preciocombustible',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Usuario'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='idZona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.Zona'),
        ),
    ]
