# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='preciocombustible',
            name='username',
        ),
    ]
